# LLM Configuration for Trading Bot
agents:
  llm_model: "gpt-4.1-mini"               # or "gpt-4", "gpt-3.5-turbo"
  use_llm_confirmation: true             # Enable/disable LLM usage
  signal_confidence_threshold: 0.6       # Signal detection threshold
  decision_confidence_threshold: 0.7     # Decision making threshold

# Backtesting settings
backtest:
  start: "2024-01-01"
  end: "2024-12-31"
  initial_capital: 10000.0

# Data settings  
data:
  source: "yahoo"
  interval: "1d"
